### ISSUE TITLE
Can't resolve 'child_process'

### ISSUE THREAD

**Issue by Navyasri-Gurram** [luthraG/image-watermark#15]
Getting error as Can't resolve 'child_process'

var watermark = require('image-watermark');
watermark.embedWatermark(require("./00030.jpg") , { 'text': 'sample watermark' });

**Comment by brianpilati** [comment]
I am seeing the same error from an installing today.

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

@Navyasri-Gurram Any thoughts on this error?

**Comment by jeremylzy** [comment]
@brianpilati I have the same error,Have you solved the problem? Tks

**Comment by brianpilati** [comment]
@jeremylzy You need to install `ImageMagick`.

**Comment by nibiru2O12** [comment]
having the same problem.. installed this [https://www.npmjs.com/package/imagemagick](url) but still throwing error.

**Comment by bruceleong** [comment]
Has this error been fixed? I have tried using the API instructions with no luck and the same error as above.

**Comment by NIVJAIN** [comment]
No, not yet fixed, i created a python script.

Sent from my iPhone6+
 
With Best Regards
Mit freundlichen Grüßen und Liebe Grüße aus Singapur🇩🇪

**Comment by sushantpaudel** [comment]
This problem is caused because your system could not find a command **identify**. This problem can be resolved by installing [ImageMagick](https://imagemagick.org/script/download.php) from the official site and go to [this](https://stackoverflow.com/questions/32781975/node-js-cant-see-imagemagick-on-windows-7/43713441#43713441) answer if you are still facing the same error after the installation.

The problem of this error is, there is really little information in the error message to tell you where the root cause is. I found a suitable answer to get to the root cause of the error from [here](https://stackoverflow.com/a/27883443/7514132). And, read the comments for further information and get a more brief cause of the error.

**Comment by zmarwa** [comment]
@NIVJAIN could you please paste your python code !
Thks!
