### ISSUE TITLE
Command timed out on large files

### ISSUE THREAD

**Issue by pizzolante** [luthraG/image-watermark#27]
Hi, when I try to process large files (up to 200mb), obtain this:

```
/home/leo/node_modules/image-watermark/watermark.js:206
                throw new Error('Image-Watermark::embedWatermark : Unable to process image file : ' + err);
                ^

Error: Image-Watermark::embedWatermark : Unable to process image file : Error: Command timed out:
    at /home/leo/node_modules/image-watermark/watermark.js:206:11
    at Accumulator.callback (/usr/lib/node_modules/imagemagick/imagemagick.js:165:5)
    at Accumulator.finish (/usr/lib/node_modules/imagemagick/imagemagick.js:60:55)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/imagemagick/imagemagick.js:93:11)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)

```

lib version: 

```
leo@leo:~/src$ gs --version
9.50

leo@leo:~/src$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib


```
Any suggestion?
Thanks in advance

**Comment by cuongdevjs** [comment]
what's your solution? I'm facing this issue.
