### ISSUE TITLE
image_watermark not working

### ISSUE THREAD

**Issue by ghost** [luthraG/image-watermark#29]
Error: spawn identify ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)  
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {     
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn identify',
  path: 'identify',
  spawnargs: [ '-verbose', 'D:\\salary1.pdf' ]
}

**Comment by Tellarion** [comment]
apt-get install imagemagick
