### ISSUE TITLE
Trying the Sample and getting: Error: spawn identify ENOENT

### ISSUE THREAD

**Issue by sougiovn** [luthraG/image-watermark#8]
I'm trying to do the Sample with a .pdf or .png files and I'm getting this error.

I'm using node v7.7.1

![screen shot 2017-03-15 at 19 56 51](https://cloud.githubusercontent.com/assets/4052932/23974353/966a5756-09b9-11e7-9387-de5023841681.png)

**Comment by martlo** [comment]
You need to install ImageMagick on your computer before running this.

**Comment by mdaronco** [comment]
This is happening to me too. I've installed the required dependencies (imagemagick and node-ratify).  Did anyone find a solution?

**Comment by chping2125** [comment]
I installed ImageMagick , but still being error

**Comment by naeem-gitonga** [comment]
@chping2125 did you find a solution to the error?

**Comment by swapnilkadam92** [comment]
I am also getting same error. Is there any solution?

**Comment by NIVJAIN** [comment]
i am getting the same error.

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn identify ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)

**Comment by piraveen** [comment]
Thanks @martlo !

Installing **imagemagick** fixed the issue for me on Mac OSX

1. Install with Homebrew `brew install imagemagick`
2. Update imagemagick symlinks **if necessary** `brew link imagemagick --overwrite`

And try again 😉

**Comment by jeremylzy** [comment]
I installed ImageMagick , but still being error

**Comment by piraveen** [comment]
You may also need to install "ghostscript"

1. Install with Homebrew `brew install ghostscript`
2. Update imagemagick symlinks if necessary `brew link imagemagick --overwrite`
And try again 😉

**Comment by zhangshichuan** [comment]
Image-Watermark::embedWatermark : Error in applying watermark : Error: Command failed: convert-im6.q16: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1361.

**Comment by harshitgupta** [comment]
I had trouble running it with `node v10.*`. Worked fine with `node v8.*`

**Comment by wasurocks** [comment]
It's working! You need to just `brew install imagemagick`

I followed @piraveen 's comment and it works like a charm!

**Comment by justfathi** [comment]
> I installed ImageMagick , but still being error

How did you install it?

**Comment by drizzt00s** [comment]
I am confused on this for 7 hours having no clues how to fix this. I installed ImageMagick and it is in Path, still got Error: spawn identify ENOENT. anyone knows how to fix this?

**Comment by lanlee1988** [comment]
I have the problem of brew install imagemagick on windows, anyone knows the solution?

**Comment by piraveen** [comment]
@lanlee1988 `brew` is for Mac OSX. You can download the binaries for windows directly from Imagemagick official website => https://imagemagick.org/script/download.php#windows

> I have the problem of brew install imagemagick on windows, anyone knows the solution?

**Comment by piraveen** [comment]
@justfathi @drizzt00s 
Is your OS Mac OSX ? If so, you need to update the symlinks `brew link imagemagick --overwrite`
